[package]
name = "tween"
version = "1.0.0"
edition = "2021"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sanbox-irl/tween"
description = "A tweening library for games"
categories = ["rendering::data-formats", "game-development"]

[features]
default = ["std"]
std = []

[dependencies]
libm = { version = "0.2.2", optional = true }
glam = { version = "0.20", optional = true }

[dev-dependencies]
approx = "0.5"
easer = "0.2.1"
